notices = {
    "0.19.0": "",
    "0.20.0": "",
    "0.21.0": "",
    "0.22.0": "",
    "0.23.0": "",
    "0.23.1": "",
    "0.24.0": "Warning: Gym version v0.24.0 has a number of critical issues with `gym.make` such that the `reset` and `step` functions are called before returning the environment. It is recommend to downgrading to v0.23.1 or upgrading to v0.25.1",
    "0.24.1": "Warning: Gym version v0.24.1 has a number of critical issues with `gym.make` such that environment observation and action spaces are incorrectly evaluated, raising incorrect errors and warning. It is recommend to downgrading to v0.23.1 or upgrading to v0.25.1",
    "0.25.0": "",
    "0.25.1": "",
    "0.25.2": "",
    "0.26.0": "All development of Gym has been moved to Gymnasium, a new package in the Farama Foundation that's maintained by the same team of developers who have maintained Gym for the past 18 months. Users of Gym v0.26.0 (your current version) can switch to the newest release of Gymnasium (v0.27.0) by simply replacing `import gym` with `import gymnasium as gym` with no additional changes. Gym is not planned to receive any future updates or bug fixes, and no further breaking changes will be made to the core API in Gymnasium. Users are encouraged to upgrade to Gymnasium at their earliest convenience.",
    "0.26.1": "All development of Gym has been moved to Gymnasium, a new package in the Farama Foundation that's maintained by the same team of developers who have maintained Gym for the past 18 months. Users of Gym v0.26.1 (your current version) can switch to the newest release of Gymnasium (v0.27.0) by simply replacing `import gym` with `import gymnasium as gym` with no additional changes. Gym is not planned to receive any future updates or bug fixes, and no further breaking changes will be made to the core API in Gymnasium. Users are encouraged to upgrade to Gymnasium at their earliest convenience.",
    "0.26.2": "All development of Gym has been moved to Gymnasium, a new package in the Farama Foundation that's maintained by the same team of developers who have maintained Gym for the past 18 months. Users of Gym v0.26.2 (your current version) can switch to the newest release of Gymnasium (v0.27.0) by simply replacing `import gym` with `import gymnasium as gym` with no additional changes. Gym is not planned to receive any future updates or bug fixes, and no further breaking changes will be made to the core API in Gymnasium. Users are encouraged to upgrade to Gymnasium at their earliest convenience.",
}
